### ISSUE TITLE
upstream breaking changes in 2.0.0

### ISSUE THREAD

**Issue by cs-shadowbq** [zeronetworks/WTF-WFP#2]
https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/issues/72

**Comment by cs-shadowbq** [comment]
Install-Module -Name NtObjectManager -RequiredVersion 1.1.33

**Comment by sagiesec** [comment]
thank you. I've updated the documentation.
Perhaps I'll update the code to work with the latest version of NtObjectManager

**Comment by sagiesec** [comment]
From 2.0.0 should support the new NtObjectManager version
